name: Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: |
          npm i 

      - run: |
          npx playwright install chromium --with-deps

      - name: test
        run: |
          npm t

